Input = {
        'reverse':{1: {'geography': ['us'], 'products': [], 'market': []},
            2: {'geography': ['canada'], 'products': [], 'market': []},
            3: {'geography': ['mexico'], 'products': [], 'market': []},
            4: {'geography': ['germany'], 'products': [], 'market': []},
            5: {'geography': ['brazil'], 'products': [], 'market': []},
            6: {'geography': ['spain'], 'products': [], 'market': []},
            7: {'geography': ['italy'], 'products': [], 'market': []},
            8: {'geography': ['uk'], 'products': [], 'market': []},
            9: {'geography': ['japan'], 'products': [], 'market': []},
            10: {'geography': ['australia'], 'products': [], 'market': []},
            11: {'geography': ['us'], 'products': ['mouthwash'], 'market': []},
            12: {'geography': ['canada'], 'products': ['mouthwash'], 'market': []},
            13: {'geography': ['mexico'], 'products': ['mouthwash'], 'market': []},
            14: {'geography': ['germany'], 'products': ['mouthwash'], 'market': []},
            15: {'geography': ['brazil'], 'products': ['mouthwash'], 'market': []},
            16: {'geography': ['spain'], 'products': ['mouthwash'], 'market': []},
            17: {'geography': ['italy'], 'products': ['mouthwash'], 'market': []},
            18: {'geography': ['uk'], 'products': ['cars'], 'market': []},
            19: {'geography': ['uk'], 'products': ['mouthwash'], 'market': []},
            20: {'geography': ['uk'], 'products': ['food'], 'market': []},
            21: {'geography': ['uk'], 'products': ['mouthwash', 'toothpaste'], 'market': []},
            22: {'geography': ['uk'], 'products': ['mouthwash', 'toothpaste'], 'market': ['wallmart']},
            23: {'geography': ['japan'], 'products': ['mouthwash'], 'market': []},
            24: {'geography': ['japan'], 'products': ['mouthwash', 'toothpaste'], 'market': []},
            25: {'geography': ['japan'], 'products': ['mouthwash', 'toothpaste'], 'market': ['wallmart']},
            26: {'geography': ['japan'], 'products': ['mouthwash', 'toothpaste'], 'market': ['silpo']},
            27: {'geography': ['japan'], 'products': ['mouthwash'], 'market': ['wallmart']},
            28: {'geography': ['australia'], 'products': ['mouthwash'], 'market': []}},
        'direct':{
           ('australia',): {('total',): {('total',): 10},
                            ('mouthwash',): {('total',): 28}
                            },
           ('japan',): {('total',): {('total',): 9},
                        ('mouthwash', 'toothpaste'): {('total',): 24, ('silpo',): 26, ('wallmart',): 25},
                        ('mouthwash',): {('total',): 23, ('wallmart',): 27}
                        },
            ('italy',): {('total',): {('total',): 7},
                         ('mouthwash',): {('total',): 17}
                         },
            ('uk',): {('total',): {('total',): 8},
                      ('cars',): {('total',): 18},
                      ('mouthwash',): {('total',): 19},
                      ('food',): {('total',): 20},
                      ('mouthwash', 'toothpaste'): {('total',): 21, ('wallmart',): 22}},
            ('us',): {('total',): {('total',): 1}, ('mouthwash',): {('total',): 11}},
            ('brazil',): {('total',): {('total',): 5}, ('mouthwash',): {('total',): 15}},
            ('canada',): {('total',): {('total',): 2}, ('mouthwash',): {('total',): 12}},
            ('mexico',): {('total',): {('total',): 3}, ('mouthwash',): {('total',): 13}},
            ('germany',): {('total',): {('total',): 4}, ('mouthwash',): {('total',): 14}},
            ('spain',): {('total',): {('total',): 6}, ('mouthwash',): {('total',): 16}}},
        'order':['geography', 'products', 'market']
        }
