landing:
  top_menu:
    landing: Home
    dashboard: Dashboard
    comparison: Comparison
    scenarios: Scenarios
    simulator: Simulator
    help: Help
  logout:
    label: Log Out

dashboard:
  selector:
    items_title: Categories
    search_title: Search
    search_placeholder: Type here
    search_clear: Clear search
    selected_title: Selected
    not_found_items: Not found items
    apply_button: Apply
    do_not_proceed: You need to select something to proceed
    cancel_button: Cancel
  general:
    forecast_block: Forecast
    decomposition_block: Decomposition
    insights_block: Insights
    drivers_summary_block: Drivers Summary
    dashboard_tab: Dashboard
    drivers_summary_tab: Drivers Summary
    drivers_details_tab: Driver\s Details
    value: Value
    growth_rate: Growth rate
    collapse: Collapse
    expand: Expand
    explore: Explore
    tab_all: All
    absolute: Absolute
    growth_cagr: Growth (CAGR)
    driver_contribution: Driver Contribution to Sales Growth
    driver_change_cagr: Driver Change (CAGR)
    driver: Driver
    metric: Metric
    cagr: CAGR
    sub_drivers_dynamic: Sub-driver\s dynamic
    sub_drivers_impact: Sub-driver\s impact
    fact: Fact

admin:
  admin_tools:
    create_user_label: Create New User 
    edit_user_label: Show / Edit user 
    delete_user_button: Delete User 
    reset_user_password_button: Reset Password 
    add_user_form_button: Create User 
    edit_user_form_button: Edit User 
    user_is_not_selected_message: User is not selected 
    users_list_title: Users List
  
scenarios:
  scenarios:
    recent_actions_header_name: Recent Actions 
    work_list_header_name: Work List 
    filter_section_name: Filters
    filter_section_favorites_label: Favorites
    filter_section_shared_label: Shared
    filter_section_local_label: Local
    filter_section_drafts_label: Drafts
    filter_section_final_label: Final
    search_input_placeholder: Search
    show_multiselect_label: Show multiselect
    create_new_scenario_label: Create New
    finalize_scenario_label: Finalize
    share_scenario_label: Share
    delete_scenario_label: Delete
    table_name_row: Name
    table_author_row: Author
    table_shared_row: Shared
    table_shared_local_value: Local
    table_description_row: Description
    table_modified_row: Modified
    table_status_row: Status
    table_worklist_tooltip: Worklist
    table_add_to_favorites_tooltip: Add to Favorites
    table_remove_from_favorites_tooltip: Remove from Favorites
    table_copy_tooltip: Copy
    table_edit_tooltip: Edit
    table_go_scenario_tooltip: Go Scenario
    not_found_criteria_scenarios_message: No records found satisfying your criteria
    not_found_scenarios_message: Not found scenarios